import { GlobalContextProvider } from "@/context/store";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NimbleRx Take home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          <main className="flex min-h-screen flex-col p-24">
            <nav className="flex justify-end p-4">
              <Link href="/">Home</Link>
            </nav>
            {children}
          </main>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
